include(
	"breeze-core",
	"breeze-dsl",
	"breeze-functional",
	"breeze-generator",
	"breeze-http",
	"breeze-javafx",
	"breeze-logger",
	"breeze-reflect",
	"breeze-serialization",
	"breeze-time",
	"breeze-unstable"
)
